language: node_js
node_js:
  - "node"
services:
  - docker

branches:
  only:
    - master

before_install:
  - npm i
  - npm run-script test-setup

script:
  - npm test

after_script:
  - npm run-script test-teardown

